module.exports = class Data1715806980113 {
    name = 'Data1715806980113'

    async up(db) {
        await db.query(`CREATE TABLE "bridge_transfer" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "status" character varying(15) NOT NULL, "fee_paid" numeric NOT NULL, "source_chain_id" numeric NOT NULL, "source_transfer_id" numeric NOT NULL, "source_account" text NOT NULL, "dest_chain_id" numeric NOT NULL, "dest_account" text NOT NULL, "created_at_block" integer NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "created_tx_hash" text NOT NULL, "completed_at_block" integer, "completed_at_timestamp" TIMESTAMP WITH TIME ZONE, "completed_tx_hash" text, CONSTRAINT "PK_fab0727701656a3e6c320fca6e9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_53080eeff656a11a055951f0e8" ON "bridge_transfer" ("status") `)
        await db.query(`CREATE INDEX "IDX_67f37b0f93276ecd918dc3af86" ON "bridge_transfer" ("source_chain_id") `)
        await db.query(`CREATE INDEX "IDX_9d02e5753f5052271ff370c1f6" ON "bridge_transfer" ("source_transfer_id") `)
        await db.query(`CREATE INDEX "IDX_bc5ac7a9e6d71f087e4812cc4e" ON "bridge_transfer" ("source_account") `)
        await db.query(`CREATE INDEX "IDX_edd947da57d507d8022cee1b08" ON "bridge_transfer" ("dest_chain_id") `)
        await db.query(`CREATE INDEX "IDX_ee5e279f57a10f2a713ace3ed5" ON "bridge_transfer" ("dest_account") `)
        await db.query(`CREATE TABLE "evm_bridge_config" ("id" character varying NOT NULL, "status" character varying(6) NOT NULL, "bridging_fee" numeric NOT NULL, "minting_limits" jsonb NOT NULL, "total_minted" numeric NOT NULL, "total_burned" numeric NOT NULL, CONSTRAINT "PK_8d0d9be7b260dfb3aa0a9592efa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "evm_bridge_transfer_to_joystream_requested_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "amount" numeric NOT NULL, "eth_requester" text NOT NULL, "eth_transfer_id" numeric NOT NULL, "joy_dest_account" text NOT NULL, CONSTRAINT "PK_3adaebf1da03f59222adfabf81f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6474e195d55d75012dc425fcdd" ON "evm_bridge_transfer_to_joystream_requested_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_bridge_transfer_to_eth_completed_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "joy_transfer_id" numeric NOT NULL, "eth_dest_address" text NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_17d82808f00d758405c32193bff" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_2a9089ddd5c529a71c2239b5a0" ON "evm_bridge_transfer_to_eth_completed_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_bridge_fee_changed_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "fee" numeric NOT NULL, CONSTRAINT "PK_b623b6f450af34bb80e45d7aed1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6b3c523b750926a0c948d2caea" ON "evm_bridge_fee_changed_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_bridge_fees_withdrawn_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "amount" numeric NOT NULL, "destination" text NOT NULL, CONSTRAINT "PK_5f026884f13b1e93e4e4447963e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c9c55f86f1362b8b64e3ba5734" ON "evm_bridge_fees_withdrawn_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_bridge_status_changed_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(6) NOT NULL, CONSTRAINT "PK_48ec466cca7d4921c590b5fac7e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8369485d127fd3eea613758105" ON "evm_bridge_status_changed_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_bridge_minting_limits_updated_event" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "tx_hash" text NOT NULL, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "period_length" integer NOT NULL, "period_limit" numeric NOT NULL, CONSTRAINT "PK_0d76fc70054dd06ef3de20776a9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e720f154623e4b89a56f37b44b" ON "evm_bridge_minting_limits_updated_event" ("chain_id") `)
        await db.query(`CREATE TABLE "evm_timelock_call" ("id" character varying NOT NULL, "chain_id" numeric NOT NULL, "call_id" text NOT NULL, "status" character varying(9) NOT NULL, "created_at_block" integer NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "created_tx_hash" text NOT NULL, "executed_at_block" integer, "executed_at_timestamp" TIMESTAMP WITH TIME ZONE, "executed_tx_hash" text, "cancelled_at_block" integer, "cancelled_at_timestamp" TIMESTAMP WITH TIME ZONE, "cancelled_tx_hash" text, "call_target" text NOT NULL, "call_value" numeric NOT NULL, "call_data" text NOT NULL, "call_signature" text, "call_args" text, "predecessor" text, "salt" text, "delay_done_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_b396eb1dbdce864526244730a88" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f852e8a783fa16355763fd26b0" ON "evm_timelock_call" ("chain_id") `)
        await db.query(`CREATE INDEX "IDX_4105b818ff699d64882f3dfa82" ON "evm_timelock_call" ("call_id") `)
    }

    async down(db) {
        await db.query(`DROP TABLE "bridge_transfer"`)
        await db.query(`DROP INDEX "public"."IDX_53080eeff656a11a055951f0e8"`)
        await db.query(`DROP INDEX "public"."IDX_67f37b0f93276ecd918dc3af86"`)
        await db.query(`DROP INDEX "public"."IDX_9d02e5753f5052271ff370c1f6"`)
        await db.query(`DROP INDEX "public"."IDX_bc5ac7a9e6d71f087e4812cc4e"`)
        await db.query(`DROP INDEX "public"."IDX_edd947da57d507d8022cee1b08"`)
        await db.query(`DROP INDEX "public"."IDX_ee5e279f57a10f2a713ace3ed5"`)
        await db.query(`DROP TABLE "evm_bridge_config"`)
        await db.query(`DROP TABLE "evm_bridge_transfer_to_joystream_requested_event"`)
        await db.query(`DROP INDEX "public"."IDX_6474e195d55d75012dc425fcdd"`)
        await db.query(`DROP TABLE "evm_bridge_transfer_to_eth_completed_event"`)
        await db.query(`DROP INDEX "public"."IDX_2a9089ddd5c529a71c2239b5a0"`)
        await db.query(`DROP TABLE "evm_bridge_fee_changed_event"`)
        await db.query(`DROP INDEX "public"."IDX_6b3c523b750926a0c948d2caea"`)
        await db.query(`DROP TABLE "evm_bridge_fees_withdrawn_event"`)
        await db.query(`DROP INDEX "public"."IDX_c9c55f86f1362b8b64e3ba5734"`)
        await db.query(`DROP TABLE "evm_bridge_status_changed_event"`)
        await db.query(`DROP INDEX "public"."IDX_8369485d127fd3eea613758105"`)
        await db.query(`DROP TABLE "evm_bridge_minting_limits_updated_event"`)
        await db.query(`DROP INDEX "public"."IDX_e720f154623e4b89a56f37b44b"`)
        await db.query(`DROP TABLE "evm_timelock_call"`)
        await db.query(`DROP INDEX "public"."IDX_f852e8a783fa16355763fd26b0"`)
        await db.query(`DROP INDEX "public"."IDX_4105b818ff699d64882f3dfa82"`)
    }
}
